FROM registry.access.redhat.com/ubi9/openjdk-25-runtime:1.24

ENV LANGUAGE='en_US:en'
ENV QUARKUS_PROFILE='sqlite'
ENV SYNAPSE_SQLITE_DB_PATH='/data/synapse.sqlite'

USER root
RUN mkdir -p /data \
	&& chown -R 185:0 /data \
	&& chmod -R g+rwX /data

COPY --chown=185:0 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185:0 target/quarkus-app/*.jar /deployments/
COPY --chown=185:0 target/quarkus-app/app/ /deployments/app/
COPY --chown=185:0 target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185
ENV JAVA_OPTS_APPEND='-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager'
ENV JAVA_APP_JAR='/deployments/quarkus-run.jar'

ENTRYPOINT ["/opt/jboss/container/java/run/run-java.sh"]

